# Generated by Django 3.2.4 on 2023-07-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='layersmodel',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='layersmodel',
            name='text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
