# Generated by Django 3.2.4 on 2023-07-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afmanager', '0002_auto_20230704_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layersmodel',
            old_name='layer_pos',
            new_name='layer_posx',
        ),
        migrations.AddField(
            model_name='layersmodel',
            name='layer_posy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
